rsvpapp:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
    - "8080:8080"
  links:
    - rsvpdb
rsvpdb:
  image: postgres:9.4
  ports:
    - "5432:5432"
